<?php

namespace Facture\FreeMobileBundle\Repository;

use Doctrine\ORM\EntityRepository;
//~ use Doctrine\ORM\Query\ResultSetMapping;

/**
 * AppelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppelRepository extends EntityRepository
{
	public function findAppelNb()
	{
		$query = $this->_em->createQuery('SELECT COUNT(a) FROM FactureFreeMobileBundle:Appel a');
		return $query->getResult();
	}
	
	public function findDateFirstCall($id)
	{
		$query = $this->_em->createQuery('SELECT a.date FROM FactureFreeMobileBundle:Appel a WHERE a.contact = :id ORDER BY a.id ASC');
		$query->setParameter('id', $id);
		$query->setMaxResults(1);
		$query->setFirstResult(0);
		return $query->getResult();
	}
	
	public function findDateLastCall($id)
	{
		$query = $this->_em->createQuery('SELECT a.date FROM FactureFreeMobileBundle:Appel a WHERE a.contact = :id ORDER BY a.id DESC');
		$query->setParameter('id', $id);
		$query->setMaxResults(1);
		$query->setFirstResult(0);
		return $query->getResult();
	}
	
	//~ public function findSum($id)
	//~ {
		//~ $rsm = new ResultSetMapping();
		//~ //$rsm->addFieldResult('a', 'sum', 'sum');
		//~ //$rsm->addRootEntityFromClassMetadata('FactureFreeMobileBundle:Appel', 'a');
		//~ 
		//~ $query = $this->_em->createNativeQuery('SELECT SEC_TO_TIME(sum(TIME_TO_SEC(a.duree))) AS sum FROM facture__appel a WHERE a.contact_id = :id', $rsm);
		//~ $query->setParameter('id', $id);
		//~ return $query->getResult();
	//~ }
}
