<?php

namespace Facture\FreeMobileBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MMSRepository extends EntityRepository
{
	public function findMMSNb()
	{
		$query = $this->_em->createQuery('SELECT COUNT(m) FROM FactureFreeMobileBundle:MMS m');
		return $query->getResult();
	}
	
	public function findDateFirstMMS($id)
	{
		$query = $this->_em->createQuery('SELECT m.date FROM FactureFreeMobileBundle:MMS m WHERE m.contact = :id ORDER BY m.id ASC');
		$query->setParameter('id', $id);
		$query->setMaxResults(1);
		$query->setFirstResult(0);
		return $query->getResult();
	}
	
	public function findDateLastMMS($id)
	{
		$query = $this->_em->createQuery('SELECT m.date FROM FactureFreeMobileBundle:MMS m WHERE m.contact = :id ORDER BY m.id DESC');
		$query->setParameter('id', $id);
		$query->setMaxResults(1);
		$query->setFirstResult(0);
		return $query->getResult();
	}
}
